### ISSUE TITLE
DK1 Not detected on Windows 10

### ISSUE THREAD

**Issue by demonixis** [simlrh/OSVR-OpenHMD#1]
Hi,

First I want to thank you for creating this plugin for the DK1/2!

I have a DK1 and Windows 10, When I plug it I have a black screen and it's not detected. Do you know how to fix that?

**Comment by simlrh** [comment]
Hi, thanks for the report.

Can you paste the output from osvr_print_tree.exe?

Do you have the official Oculus runtime installed as well? I haven't tested with that installed.

Did you use the binaries or build from source?

I'm using a DK1 on Windows 10 so I know that it _can_ work, but not sure what the issues might be. It's a very short plugin and it's easy to add in `std::cout << "Debugging messages" << std::endl;` to find out if ohmd has started up correctly, how many devices it found, etc. 

Actually, autodetection of the rift is based on comparing the product name string, perhaps your product name is different to mine.

**Comment by demonixis** [comment]
Hi,

I think that it's a problem with my hardware. Windows doesn't detect my HMD so it's not related to your plugin. Anyway, I'll give it a new try with the DK2, I know that this one works well ;)
