### ISSUE TITLE
Bad pixel smear with DK2 OMLED display

### ISSUE THREAD

**Issue by booty156** [simlrh/OSVR-OpenHMD#5]
How can I solve this? I've correctly added my display to OSVR. But when I moved about the colors smear and it's really bad

**Comment by booty156** [comment]
If I watch a youtube video in the dk2 display there is no smear but when I start OSVR and load the D3D there is

**Comment by simlrh** [comment]
I don't believe this is a tracking issue, seems to be on the display end, which this plugin has no control over. 

Just a guess from googling, but perhaps your display is running at full persistence. Make sure refresh rate is a 75Hz or try direct mode. Beyond that I don't think I can help.

**Comment by booty156** [comment]
Ok thanks it is running at 75hz, but I cannot get the DK2 to work in direct mode. Also if I invert the screen so it is upside down it goes away.

**Comment by simlrh** [comment]
Would it work if you inverted the screen then went into Oculus_Rift_DK2.json and set swap_eyes:1 and rotate_180:1 for both eyes?

**Comment by booty156** [comment]
I'll try that now thanks

**Comment by booty156** [comment]
![image](https://cloud.githubusercontent.com/assets/20386503/26725276/ab62e3a2-4795-11e7-9573-020c3d826d67.png)

I get this error

**Comment by booty156** [comment]
Ok, working now but problem still exist

**Comment by booty156** [comment]
Ok so I have everything working inverted, can I invert the headtracking so when I move up = move down and left = right ect. How can I do this do I need to edit your plugin?

**Comment by simlrh** [comment]
No, it can be done in server config, but I wouldn't be able to do it without being able to experiment myself. If you ask in the subreddit about how to do this you might have some luck.
