### ISSUE TITLE
Is it possible to upload the windows binaries?

### ISSUE THREAD

**Issue by deadpahn** [simlrh/OSVR-OpenHMD#9]
First, big thanks for bring back the DK1! It's been collecting dust because nothing is compatible with it anymore. I was wondering if it is at all possible for someone to compile a windows binary of this plugin? I think it would save a lot of people time and help be more accessible to people.

Thanks!

**Comment by simlrh** [comment]
https://github.com/simlrh/OSVR-OpenHMD/releases
